favicon: /favicon.ico
banner: /images/webstack_banner_cn.png

logo:
  expanded: /images/logo.png
  collapsed: /images/logo-2.png
  dark: /images/logo.png

flag:
  - name: Chinese
    default: true
    icon: flag-cn
    index: /index.html

search: true

userDefinedSearchData:
  custom: true
  thisSearch: https://www.google.com/search?q=
  thisSearchIcon: url(https://afox-1256168983.cos.ap-shanghai.myqcloud.com/20220814112304.png)
  hotStatus: true
  data:
    - name: Google
      img:  url(https://afox-1256168983.cos.ap-shanghai.myqcloud.com/20220814112304.png)
      url: https://www.google.com/search?q=

# githubCorner: '<a href="https://github.com/HCLonely/hexo-theme-webstack" class="github-corner" aria-label="View source on GitHub"><svg width="80" height="80" viewBox="0 0 250 250" style="fill:#151513; color:#fff; position: absolute; top: 0; border: 0; right: 0;" aria-hidden="true"><path d="M0,0 L115,115 L130,115 L142,142 L250,250 L250,0 Z"></path><path d="M128.3,109.0 C113.8,99.7 119.0,89.6 119.0,89.6 C122.0,82.7 120.5,78.6 120.5,78.6 C119.2,72.0 123.4,76.3 123.4,76.3 C127.3,80.9 125.5,87.3 125.5,87.3 C122.9,97.6 130.6,101.9 134.4,103.2" fill="currentColor" style="transform-origin: 130px 106px;" class="octo-arm"></path><path d="M115.0,115.0 C114.9,115.1 118.7,116.5 119.8,115.4 L133.7,101.6 C136.9,99.2 139.9,98.4 142.2,98.6 C133.8,88.0 127.5,74.4 143.8,58.0 C148.5,53.4 154.0,51.2 159.7,51.0 C160.3,49.4 163.2,43.6 171.4,40.1 C171.4,40.1 176.1,42.5 178.8,56.2 C183.1,58.6 187.2,61.8 190.9,65.4 C194.5,69.0 197.7,73.2 200.1,77.6 C213.8,80.2 216.3,84.9 216.3,84.9 C212.7,93.1 206.9,96.0 205.4,96.6 C205.1,102.4 203.0,107.8 198.3,112.5 C181.9,128.9 168.3,122.5 157.7,114.1 C157.9,116.9 156.7,120.9 152.7,124.9 L141.0,136.5 C139.8,137.7 141.6,141.9 141.8,141.8 Z" fill="currentColor" class="octo-body"></path></svg></a><style>.github-corner:hover .octo-arm{animation:octocat-wave 560ms ease-in-out}@keyframes octocat-wave{0%,100%{transform:rotate(0)}20%,60%{transform:rotate(-25deg)}40%,80%{transform:rotate(10deg)}}@media (max-width:500px){.github-corner:hover .octo-arm{animation:none}.github-corner .octo-arm{animation:octocat-wave 560ms ease-in-out}}</style>'

expandAll: true
menu:
  - name: 数据分析
    icon: far fa-star
    config: dataAnalyze
  - name: 数据查询
    icon: far fa-star
    config: dataScan
  - name: NFT
    icon: far fa-star
    config: nft
  - name: 开发教程
    icon: far fa-star
    config: devTutorial
  - name: 节点提供商
    icon: far fa-star
    config: nodeProvider
  # - name: 其他工具
  #   icon: fas fa-tools
  #   submenu:
  #     - name: 开发工具
  #       icon: fas fa-tools
  #       config: devTools
  #     - name: 我的博客
  #       icon: fas fa-blog
  #       config: myBlog

dataScan:
  - name: EtherScan
    url:  https://etherscan.io/
    img:  https://afox-1256168983.cos.ap-shanghai.myqcloud.com/20220814094411.png
    description: ETH 智能链浏览器
  - name: BSCScan
    url:  https://bscscan.com/
    img:  https://afox-1256168983.cos.ap-shanghai.myqcloud.com/20220814094308.png
    description: BNB 智能链浏览器
  - name: PolygonScan
    url:  https://polygonscan.com/
    img:  https://polygonscan.com/images/favicon.ico
    description: polygon 智能链浏览器
  - name: Solscan
    url:  https://solscan.io/
    img:  https://afox-1256168983.cos.ap-shanghai.myqcloud.com/20220814094532.png
    description: SolScan 智能链浏览器
  - name: Oklink
    url:  https://www.oklink.com/zh-cn
    img:  https://afox-1256168983.cos.ap-shanghai.myqcloud.com/20220814094702.png
    description: 聚合区块链浏览器
  - name: DeBank
    url:  https://debank.com/
    img:  /images/logos/debank.svg
    description: 资产聚合查询
  - name: Coingecko
    url:  https://www.coingecko.com/
    img:  /images/logos/coingecko.jpeg 
    description: 加密货币汇率、图表和加密货币市值
  - name: Coinmarketcap
    url:  https://coinmarketcap.com
    img:  /images/logos/coinmarketcap.jpeg 
    description: 数字货币行情,最新加密货币价格走势

devTutorial:
  # - name: Child Page
  #   url: /child
  #   img: /images/logos/myblog.png
  #   description: 子页面测试
  - name: WTFSolidity
    url:  https://wtf.academy/
    img:  https://wtf.academy/img/wtflogo.png
    description: WTFSolidity 面向Web2程序员的Web3开源学院
  - name: WTFEthers
    url:  https://wtf.academy/
    img:  https://wtf.academy/img/wtflogo.png
    description: WTFSolidity 面向Web2程序员的Web3开源学院
  - name: Solidity by Example
    url:  https://solidity-by-example.org/
    img:  https://solidity-by-example.org/static/media/logo.ed2942c41ca20fd4f70a.png
    description: an introduction to Solidity with simple examples
  - name: Solidity
    url:  https://docs.soliditylang.org/
    img:  https://solidity-by-example.org/static/media/logo.ed2942c41ca20fd4f70a.png
    description: solidity doc
  

nft:
  - name: NFTscan
    url:  https://nftscan.com/
    img:  /images/logos/nftscan.png  
    description: 以太坊的 NFT 探索者
  - name: NFTnerds
    url:  https://nftnerds.ai/
    img:  https://nftnerds.ai/logo.svg
    description: NFT趋势追踪
  - name: NFTtrack
    url:  https://nfttrack.ai
    img:  /images/logos/nfttrack.jpeg
    description: 跟踪NFT鲸鱼赚钱  
  - name: NFTgo
    url:  https://nftgo.io/
    img:  https://pbs.twimg.com/profile_images/1475300585196777472/GYA3Y-EC_200x200.jpg
    description: NFT趋势追踪
  - name: NFTflip
    url:  https://review.nftflip.ai/signin?invite=TOOL3
    img:  https://pbs.twimg.com/profile_images/1524929130424283136/-KrhIWnu_200x200.jpg
    description: 帮助NFT交易者快速的抓住交易机会

dataAnalyze:
  - name: Dune.xyz
    url:  https://dune.com/
    img:  https://dune.com/assets/glyph-128w.png
    description: Dune链上数据分析平台.提供数据可视化、数据分析等功能
  - name: Nansen.ai
    url:  https://www.nansen.ai/
    img:  https://afox-1256168983.cos.ap-shanghai.myqcloud.com/20220814094157.png
    description: 链上聪明地址分析查询
  - name: Messari.io
    url:  https://messari.io/
    img:  https://afox-1256168983.cos.ap-shanghai.myqcloud.com/20220813064557.png
    description: 区块链技术指标查询工具
  - name: Glassnode 
    url:  https://glassnode.com/
    img:  https://img.foresightnews.pro/202208/8-1659600018811.png 
    description: Glassnode 提供链上数据指标分析平台
  - name: Defillama 
    url:  https://defillama.com/
    img:  https://pbs.twimg.com/profile_images/1377743719089254405/LQwS_x0l_200x200.jpg
    description: 链上DEFI面板
  - name: Datamish 
    url:  https://datamish.com/
    img:  https://afox-1256168983.cos.ap-shanghai.myqcloud.com/20220817164837.png
    description: 合约多空比
  - name: Eigenphi 
    url:  https://eigenphi.io/
    img:  /images/logos/eigenphi.png 
    description: 实时mev数据分析
  - name: Tokenterminal 
    url:  https://tokenterminal.com/
    img:  /images/logos/tokenterminal.jpeg  
    description: 实时mev数据分析
  - name: Artemis 
    url:  https://www.artemis.xyz/
    img:  /images/logo-2.png
    description: 快速查看链上数据、例如日活跃地址、日交易量等，支持多链
  - name: CoinMarketCal 
    url:  https://coinmarketcal.com
    img:  /images/logo-2.png
    description: 展示加密货币的一些最重要的事。从会议和 AMA 到新产品发布，应有尽有。
  - name: Panewslab
    url:  https://www.panewslab.com/tools
    img:  /images/logos/panewslab.jpeg 
    description: 工具导航
  - name: Watchers
    url:  https://www.watchers.pro/
    img:  /images/logos/watchers.jpeg
    description: 链上账号追踪工具箱
  - name: Metasleuth
    url:  https://metasleuth.io/
    img:  /images/logos/metasleuth.jpeg
    description: 链上账号追踪工具箱

nodeProvider:
  - name: Alchemy
    url:  https://www.alchemy.com/
    img:  https://afox-1256168983.cos.ap-shanghai.myqcloud.com/20220814095312.png
    description: web3开发者平台
  - name: ChainBase
    url:  https://chainbase.online/
    img:  /images/logos/chainbase.png  
    description: web3开发者平台
  - name: Infura
    url:  https://infura.io/
    img:  https://pbs.twimg.com/profile_images/1357501845145485316/yo6M6Y9u_200x200.jpg
    description: web3节点提供者
  - name: Blocknative
    url:  https://www.blocknative.com/
    img:  https://www.blocknative.com/hubfs/Icons%20and%20Illustrations/blocknative%20favicon.png
    description: 领先的数据提供者


devTools:
  - name: Github
    url: https://github.com/
    img: /images/logos/github.png
    description: 面向开源及私有软件项目的托管平台
  - name: Github
    url: https://github.com/
    img: /images/logos/github.png
    description: 面向开源及私有软件项目的托管平台


about:
  url: /about/
  icon: far fa-heart
  name: 关于本站

aboutPage:
  website:
    head: 关于本站
    html: '<blockquote><p>本站是<a href="https://github.com/EasyChris">EasyPlux</a>的个人导航站，收集web3高频使用的站点，开源地址：https://github.com/EasyChris/tool3-guide.git</p></blockquote>'
  webmaster:
    head: 关于站长
    name: EasyPlux
    url: https://twitter.com/easyplux
    img: https://afox-1256168983.cos.ap-shanghai.myqcloud.com/20220522145727.png
    description: 探索所有web3的可能性
    html: ''

since: 2022

busuanzi:
  enable: true
  position: footer # 'footer','sidebar'
  pv: 本站总访问量$pv
  uv: 本站总访客数$uv

custom:
  head: |- # 以下内容插入到<head></head>标签内，可设置多行，注意每行开头至少四个空格
    <!-- 直接添加html内容即可 -->
    <!-- 可设置多行 -->
  body: |- # 以下内容插入到</body>标签之前，可设置多行，注意每行开头至少四个空格
    <!-- Google tag (gtag.js) -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-6TB81WXFW1"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'G-6TB81WXFW1');
    </script>

js:
  header: /js/header.js
  footer: /js/footer.js
  jquery: /js/jquery-1.11.1.min.js
  bootstrap: /js/bootstrap.min.js
  TweenMax: /js/TweenMax.min.js
  resizeable: /js/resizeable.min.js
  joinable: /js/joinable.js
  xenonApi: /js/xenon-api.min.js
  xenonToggles: /js/xenon-toggles.min.js
  xenonCustom: /js/xenon-custom.min.js
  lozad: /js/lozad.min.js
  html5shiv: /js/html5shiv.min.js
  respond: /js/respond.min.js
  busuanzi: https://busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js

css:
  hclonely: /css/hclonely.css
  fonts: //fonts.loli.net/css?family=Arimo:400,700,400italic
  linecons: /css/fonts/linecons/css/linecons.min.css
  fontawesome: /css/fonts/fontawesome/css/all.min.css
  bootstrap: /css/bootstrap.min.css
  xenonCore: /css/xenon-core.min.css
  xenonComponents: /css/xenon-components.min.css
  xenonSkins: /css/xenon-skins.min.css
  nav: /css/nav.min.css